Ioberst17/HorrorGameJam

Assets/Editor.meta, Assets/Editor/HierarchyHighlight.cs, Assets/Editor/HierarchyHighlight.cs.meta, Assets/Scenes/Ian'sPlayground.unity, Assets/Scripts/Utilities/HierarchyHighlighter.cs, Assets/Scripts/Utilities/HierarchyHighlighter.cs.meta
- For use: Add the Hierarchy Highlighter Script from the Scripts folder to an object to let you highlight it in the hierarchy
=> Added Hierarchy Highlighter Functionality

Assets/Scenes/UI_Testing_Mason.meta, Assets/Scenes/UI_Testing_Mason/MainMenuTester_Mason.unity, Assets/Scenes/UI_Testing_Mason/MainMenuTester_Mason.unity.meta, Assets/Scenes/UI_Testing_Mason/OverworldTester_Mason.unity, Assets/Scenes/UI_Testing_Mason/OverworldTester_Mason.unity.meta, Assets/Scenes/UI_Testing_Mason/Phase1Tester_Mason.unity, Assets/Scenes/UI_Testing_Mason/Phase1Tester_Mason.unity.meta, Assets/Scenes/UI_Testing_Mason/Phase2Tester_Mason.unity, Assets/Scenes/UI_Testing_Mason/Phase2Tester_Mason.unity.meta, Assets/Scenes/UI_Testing_Mason/Phase3Tester_Mason.unity, Assets/Scenes/UI_Testing_Mason/Phase3Tester_Mason.unity.meta, Assets/Scripts/UI_Mason.meta, Assets/Scripts/UI_Mason/PauseMenuHandler_Mason.cs, Assets/Scripts/UI_Mason/PauseMenuHandler_Mason.cs.meta, Assets/Scripts/UI_Mason/SceneHandler_Mason.cs, Assets/Scripts/UI_Mason/SceneHandler_Mason.cs.meta, Assets/Scripts/UI_Mason/SceneManagerIndexBased_Mason.cs, Assets/Scripts/UI_Mason/SceneManagerIndexBased_Mason.cs.meta, ProjectSettings/EditorBuildSettings.asset
Added pause menu, main menu, scene manager, scripts in their own folder to handle all the above, and test scenes in their own folder
=> Basic UI Menus and Scene Changer

Assets/Scenes/PHASE_TESTER.unity, Assets/Scenes/PHASE_TESTER.unity.meta, Assets/Scenes/PHASE_TESTER_2.unity, Assets/Scenes/PHASE_TESTER_2.unity.meta, Assets/Scenes/PHASE_TESTER_3.unity, Assets/Scenes/PHASE_TESTER_3.unity.meta, ProjectSettings/EditorBuildSettings.asset
Created 3 Scenes from my popuptester to build off of. They are titled PHASE_TESTER_#. Put them into the build settings as well!
=> Added 3 Scenes to build from

Assets/Scenes/PHASE_TESTER.unity
=> added player data ui to PHASE_TESTER

.github/workflows/activation.yml
Adding file for GitHub Actions Continuous Integration
=> activation.yml created

.github/workflows/main.yml
Created main.yml - for CI/CD; builds Windows build during every push / pull
=> created main.yml

Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scenes/UI_Testing_Mason/PopUpTest_Mason.unity, Assets/Scripts/UI_Mason/Inventory_UI_Mason.cs, Assets/Scripts/UI_Mason/Inventory_UI_Mason.cs.meta
Created Inventory UI pop up. Press tab to open inventory. Red boxes are weapons in your inventory.
=> Added Inventory UI

Assets/Scenes/PHASE_TESTER_1.unity
Had to add a component to the event system in the main scene.
=> Added Pause Menu

Assets/Input_Actions_Mason.meta, Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scenes/UI_Testing_Mason/PopUpTest_Mason.unity, Assets/Scripts/UI_Mason/DebugCommands_Mason.cs, Assets/Scripts/UI_Mason/DebugCommands_Mason.cs.meta, Assets/Scripts/UI_Mason/DebugController_Mason.cs, Assets/Scripts/UI_Mason/DebugController_Mason.cs.meta, Assets/Scripts/UI_Mason/PlayerData_UI_Mason.cs, Assets/Scripts/UI_Mason/SceneManagerIndexBased_Mason.cs, ProjectSettings/TimelineSettings.asset
Press ` to access console. Currently there is; invincible, restart, spboost, mpboost. Type these into the console, click off the console, press enter to run.
NEXT: adding help menu to add the above text into the console. adding an enemy spawn which will spawn an enemy based on the id.
=> Created Debug/Developer Console

Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scripts/SpawnManager.cs, Assets/Scripts/UI_Mason/DebugCommands_Mason.cs, Assets/Scripts/UI_Mason/DebugController_Mason.cs
game pauses when console comes up. help shows all commands. added enemy spawn command.
=> Updates to developer console

Assets/Resources/Mixpanel.asset, Assets/Resources/Mixpanel.asset.meta, Assets/Scripts/GameController.cs, Assets/Scripts/SpawnManager.cs, Packages/manifest.json, Packages/packages-lock.json
- Added basic data tracking (see SpawnManager.cs for enemy generation tracking)
- Implemented Mixpanel
- Commented out line in GameController.cs that was causing null reference errors (Inky-related)
=> Added Data Tracking

Assets/Ink/Demos/Basic Demo.unitypackage.meta, Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scenes/UI_Testing_Mason/DialogueTester.unity
=> Added Dialogue System to Main scene

Assets/Scripts/Items/HealthKit.cs, Assets/Scripts/UI_Mason/PlayerData_UI_Mason.cs, Assets/Scripts/Utilities/ConsumablesDatabase.cs
Key: uncommented missing namespace in PlayerData_UI_Mason.cs
=> Fixed build compilation issues, commented out debug.logs

Assets/Art/Enemies/Bat/EnemyBat.prefab, Assets/Art/Enemies/BloodGolem/BloodGolem.prefab, Assets/Art/Enemies/Hellhound/EnemyHellHound.prefab, Assets/Art/Enemies/ParalysisDemon/EnemyParalysisDemon.prefab, Assets/Art/Enemies/Spider/EnemySpider.prefab, Assets/Scenes/PHASE_TESTER_1.unity
Added 2D Spot Lights to all enemies, except the Gargoyle. Increased the 2dGlobal Light intensity from 0.5 to 0.7 during testing.
=> Enemy Lighting Additions & Global Light Intensity Increase for Testing

Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scenes/UI_Testing_Mason/DialogueTester.unity, Assets/Scenes/UI_Testing_Mason/Phase1Tester_Mason.unity, Assets/Scripts/Player/Inventory/WeaponsManager.cs, Assets/Scripts/UI_Mason/Inventory_UI_Mason.cs, Assets/Scripts/UI_Mason/PlayerData_UI_Mason.cs
fixed equipping weapons through the inventory ui, slight changes to the playerdataui, added medkit ui to playerdata ui, and enabled quick health with h to use a medkit.
=> fixed issues inventory ui

Assets/Prefabs/UI Prefabs/MainMenu.prefab, Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scenes/UI_Testing_Mason/MainMenuTester_Mason.unity, Assets/Scenes/UI_Testing_Mason/Phase1Tester_Mason.unity, Assets/Scripts/UI_Mason/New_PopUpHandler_Mason.cs, Assets/Scripts/UI_Mason/New_PopUpHandler_Mason.cs.meta, Assets/Scripts/UI_Mason/PlayerData_UI_Mason.cs
General UI Updates to title screen and pause menu.
made new script for ui popup that can be attached to anything we want to put a popup on. very customizable.
=> Reworked PopUp Script

Assets/Scenes/UI_Testing_Mason/Phase1Tester_Mason.unity, Assets/Scripts/UI_Mason/ObjectiveUI.cs, Assets/Scripts/UI_Mason/ObjectiveUI.cs.meta, Assets/Scripts/UI_Mason/PlayerData_UI_Mason.cs
=> objectiveuiUpdate

Assets/Art_TSL/Prefabs_TSL/Room_Outline_TSL.prefab, Assets/Scenes/PHASE_TESTER_1.unity
Added door references to their own DoorScript in the prefab editor.
=> Edits to Outline_TSL Prefab

Assets/Resources/TextFiles/WeaponDatabase.csv, Assets/Resources/UI_Prefabs/InventoryUI.prefab, Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scripts/Classes/PlayerWeapons.cs, Assets/Scripts/Player/Inventory/WeaponsManager.cs, Assets/Scripts/UI_Mason/Inventory_UI_Mason.cs, Assets/Scripts/UI_Mason/PlayerData_UI_Mason.cs
Restyled and worked info panel inside of inventoryUI.
Info Panel shows:
-Name
-Damage/Healing/Lucidity Change
-Ammo/Amount
-Descriptions
Still need to add images for item slots.
Also in the middle of adding a use button for consumables.
=> InevntoryUI Update

Assets/Resources/UI_Prefabs/InventoryUICanvas.prefab, Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scripts/Player/Abilities/PlayerDash.cs, Assets/Scripts/UI_Mason/PlayerData_UI_Mason.cs
added dash ui and reintegrated inventory ui into phase tester 1.
made a placeholder shield cool down timer ui element as well to see if we want to add more and place them in the bottom left as shown.
=> Dash UI Added

Assets/Art/FireParticles.unitypackage.meta, Assets/Prefabs/UI Prefabs/MainMenu.prefab, Assets/Resources/UI_Prefabs/InventoryUICanvas.prefab, Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scripts/UI_Mason/PauseMenuHandler_Mason.cs
Completed:
- remade pause menu.
- added options button and menu into the pause menu.
- fixed issue with puling up controls menu while paused.,
- fixed item tab in invenotryui.
Next:
- creating objective tab menu in inventoryui.
- fix equip and use buttons.
- fix animation issue that is plaguing most buttons.
- prefab and test playerdataui.
- have objective ui pop up when it updates.
=> Pause Menu Remake

Assets/Animations_Mason/ButtonAnimations/InventoryButtons.controller, Assets/Resources/UI_Prefabs/InventoryUICanvas.prefab, Assets/Scenes/PHASE_TESTER_1.unity, Assets/Scripts/UI_Mason/Inventory_UI_Mason.cs
Some small ui updates and code updates.
=> Small Push
